fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    group:
        group_class: App\Entity\Group
    service:
        mailer: fos_user.mailer.default
    from_email:
        address: 'iprodich@gmail.com'
        sender_name: 'iprodich'
    
        # mailer: 'fos_user.mailer.twig_swift' # Works as well
    registration:
        confirmation:
            enabled: true       