version: '3'
services:
  eventos:
    build: .
    #image: "docker-apps_eventos"
    container_name: eventos
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    restart: "always"
    command: "init.sh"
    depends_on:
      - db
  
  db:
   image: webhippie/mariadb:latest
   restart: always
   container_name: mariadb
   environment:
    - MYSQL_ROOT_PASSWORD=dbpass
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=eventos
   volumes:
    - mysql:/var/lib/mysql

volumes: 
  mysql: